/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class System */

#ifndef _Included_System
#define _Included_System

namespace mini_jvm {

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     System
 * Method:    gc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lang_System_gc(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif

class Java_lang_System {
    public:
        static void register_natives(JNIEnv* env);
};

}

#endif
