/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class DarrenThread */
namespace mini_jvm {

#ifndef _Included_DarrenThread
#define _Included_DarrenThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DarrenThread
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DarrenThread_start(JNIEnv *, jobject);

/*
 * Class:     DarrenThread
 * Method:    sleepNanos
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_DarrenThread_sleepNanos(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif

class InstanceKClass;

class Java_native_DarrenThread {
    public:
        static void register_natives(JNIEnv* env);
};

}
#endif
