#ifndef DAREEN_MINIJVM_JNI_JAVA_IO_PRINTSTREAM
#define DAREEN_MINIJVM_JNI_JAVA_IO_PRINTSTREAM

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

namespace mini_jvm {
/* Header for class PrintStream */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrintStream
 * Method:    println
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL java_io_PrintStream_println_Ljava_lang_String(JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL java_io_PrintStream_println_I(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
class InstanceKClass;

class Java_io_PrintStream {
    public:
        static void register_natives(JNIEnv* env);
};

}

#endif